In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\Yash Rajput\Desktop\DataCo\DataCoSupplyChainDataset.csv",encoding ='latin')

In [3]:
pd.set_option('display.max_column',None)

In [4]:
pd.set_option('display.float_format','{:,.2f}'.format)

In [5]:
df.shape

(180519, 53)

In [29]:
df.sample(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode,Profit Margin,Delivery Delay,Orders Month,Orders Year
143320,CASH,2,1,-18.44,40.98,Late delivery,1,46,Indoor/Outdoor Games,Las Vegas,EE. UU.,Megan,2245,Johnson,Consumer,NV,1550 Broad Pine Place,"89,101.00",7,Fan Shop,36.19,-115.13,Europe,Solingen,Alemania,2245,2015-09-23 23:37:00,18222,1014,9.00,0.18,45555,49.98,-0.45,1,49.98,40.98,-18.44,Western Europe,Renania del Norte-Westfalia,CLOSED,1014,46,O'Brien Men's Neoprene Life Vest,49.98,2015-09-25 23:37:00,First Class,-36.89,1,September,2015
68267,DEBIT,4,4,-117.43,414.96,Shipping on time,0,9,Cardio Equipment,Caguas,Puerto Rico,Mary,5212,Smith,Corporate,PR,8813 Cozy Gate Hill,725.00,3,Footwear,18.22,-66.37,LATAM,Santiago de Cuba,Cuba,5212,2015-02-19 14:07:00,3398,191,84.99,0.17,8433,99.99,-0.28,5,499.95,414.96,-117.43,Caribbean,Santiago de Cuba,COMPLETE,191,9,Nike Men's Free 5.0+ Running Shoe,99.99,2015-02-23 14:07:00,Standard Class,-23.49,0,February,2015
23196,CASH,3,4,39.09,126.09,Advance shipping,0,18,Men's Footwear,Elgin,EE. UU.,Jerry,6962,Sandoval,Corporate,IL,3006 Dusty Apple Range,"60,123.00",4,Apparel,42.03,-88.29,LATAM,Mixco,Guatemala,6962,2015-02-04 02:24:00,2337,403,3.90,0.03,5846,129.99,0.31,1,129.99,126.09,39.09,Central America,Guatemala,CLOSED,403,18,Nike Men's CJ Elite 2 TD Football Cleat,129.99,2015-02-07 02:24:00,Standard Class,30.07,-1,February,2015
52786,DEBIT,4,2,65.52,181.99,Late delivery,1,48,Water Sports,Yauco,Puerto Rico,Christopher,11733,Chan,Corporate,PR,9660 Dewy Leaf Freeway,698.00,7,Fan Shop,18.03,-66.85,Europe,Stockport,Reino Unido,11733,2017-09-25 15:46:00,68413,1073,18.00,0.09,171051,199.99,0.36,1,199.99,181.99,65.52,Northern Europe,Inglaterra,COMPLETE,1073,48,Pelican Sunstream 100 Kayak,199.99,2017-09-29 15:46:00,Second Class,32.76,2,September,2017
156827,TRANSFER,2,1,67.88,138.52,Shipping canceled,0,12,Boxing & MMA,Caguas,Puerto Rico,Sharon,6338,Snyder,Consumer,PR,139 Honey Leaf Expressway,725.00,3,Footwear,18.23,-66.37,USCA,Naperville,Estados Unidos,6338,2016-07-11 13:03:00,38195,249,26.39,0.16,95354,54.97,0.49,3,164.91,138.52,67.88,US Center,Illinois,SUSPECTED_FRAUD,249,12,Under Armour Women's Micro G Skulpt Running S,54.97,2016-07-13 13:03:00,First Class,41.16,1,July,2016

In [7]:
cols = ['Customer Email','Customer Password']
for col in cols:
    print(f"{col}:",
        df[col].unique()
    )

Customer Email: ['XXXXXXXXX']
Customer Password: ['XXXXXXXXX']

Checking missing values

In [8]:
a = df.isna().mean() * 100
a.sort_values(ascending=False)

Product Description             100.00
Order Zipcode                    86.24
Customer Lname                    0.00
Customer Zipcode                  0.00
Type                              0.00
Order Profit Per Order            0.00
Order Item Cardprod Id            0.00
Order Item Discount               0.00
Order Item Discount Rate          0.00
Order Item Id                     0.00
Order Item Product Price          0.00
Order Item Profit Ratio           0.00
Order Item Quantity               0.00
Sales                             0.00
Order Item Total                  0.00
Order Region                      0.00
order date (DateOrders)           0.00
Order State                       0.00
Order Status                      0.00
Product Card Id                   0.00
Product Category Id               0.00
Product Image                     0.00
Product Name                      0.00
Product Price                     0.00
Product Status                    0.00
shipping date (DateOrders)        0.00
Order Id                          0.00
Order Country                     0.00
Order Customer Id                 0.00
Customer Fname                    0.00
Days for shipment (scheduled)     0.00
Benefit per order                 0.00
Sales per customer                0.00
Delivery Status                   0.00
Late_delivery_risk                0.00
Category Id                       0.00
Category Name                     0.00
Customer City                     0.00
Customer Country                  0.00
Customer Email                    0.00
Customer Id                       0.00
Days for shipping (real)          0.00
Customer Password                 0.00
Customer Segment                  0.00
Customer State                    0.00
Customer Street                   0.00
Department Id                     0.00
Department Name                   0.00
Latitude                          0.00
Longitude                         0.00
Market                            0.00
Order City                        0.00
Shipping Mode                     0.00
dtype: float64

Removing columns

In [9]:
# columns removed 
a=['Product Description','Order Zipcode','Customer Email','Customer Password','Product Image','Product Status']
df.drop(columns=a,errors='ignore',inplace=True)

Checking Duplicates

In [10]:
df.duplicated().sum()

0

Checking datatypes

In [11]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Product Card Id                    int64
Product Category Id                int64
Product Name                      object
Product Price                    float64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

Converting string collumns to date time

In [12]:
cols = ['shipping date (DateOrders)','order date (DateOrders)']
for col in cols:
    df[col] = pd.to_datetime(df[col],errors='coerce')

Count of Unique values in categorical columns

In [13]:
cat_col = df.select_dtypes(include='object').columns
for col in cat_col:
    print(f'\n---{col:}---')
    print(df[col].value_counts(dropna=False).head(20))

---Type---
Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

---Delivery Status---
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

---Category Name---
Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Accessories              1780
Golf Balls               1475
Girls' Apparel           1201
Golf Gloves              1070
Trade-In                  974
Video Games               838
Children's Clothing       652
Women's Clothing          650
Baseball & Softball       632
Hockey                    614
Name: count, dtype: int64

---Customer City---
Customer City
Caguas          66770
Chicago          3885
Los Angeles      3417
Brooklyn         3412
New York         1816
Philadelphia     1577
Bronx            1500
San Diego        1437
Miami            1314
Houston          1297
Las Vegas        1164
Dallas           1029
Aurora           1015
Detroit           958
Phoenix           945
San Jose          943
Cleveland         784
Lancaster         762
San Antonio       730
Memphis           707
Name: count, dtype: int64

---Customer Country---
Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64

---Customer Fname---
Customer Fname
Mary           65150
James           1835
Robert          1759
Michael         1680
David           1625
John            1446
William         1365
Joseph          1117
Jennifer        1033
Richard         1032
Elizabeth       1009
Jessica          899
Charles          898
Patricia         898
Christopher      895
Thomas           875
Matthew          864
Cynthia          838
Catherine        823
Margaret         822
Name: count, dtype: int64

---Customer Lname---
Customer Lname
Smith        64104
Johnson        989
Brown          909
Williams       869
Jones          859
Garcia         724
Wilson         675
Taylor         661
Davis          640
Moore          599
Jackson        576
Anderson       544
Martinez       513
Allen          498
Miller         495
Clark          485
Rodriguez      472
Gonzalez       443
Hall           443
Wright         424
Name: count, dtype: int64

---Customer Segment---
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

---Customer State---
Customer State
PR    69373
CA    29223
NY    11327
TX     9103
IL     7631
FL     5456
OH     4095
PA     3824
MI     3804
NJ     3191
AZ     3026
GA     2503
MD     2415
NC     1992
CO     1914
VA     1849
OR     1668
MA     1607
TN     1582
NV     1440
Name: count, dtype: int64

---Customer Street---
Customer Street
9126 Wishing Expressway        122
4388 Burning Goose Ridge       117
4720 Noble Hills Wynd          116
2878 Hazy Wagon  Thicket       113
398 Emerald Grove              109
3593 Blue Brook Acres          108
2210 Merry Leaf Row            107
6289 Rocky Way                 107
2585 Silent Autumn Landing     105
7694 Velvet Turnabout          103
141 Dewy Plaza                 103
2676 Velvet Common             102
6324 Jagged Orchard            101
7111 Cotton Blossom Estates     99
7342 Hidden Walk                99
3977 Colonial Towers            98
406 Shady Cider Corner          98
3663 Umber Cloud Arbor          98
9138 Indian Nook                97
119 Gentle Wynd                 96
Name: count, dtype: int64

---Department Name---
Department Name
Fan Shop              66861
Apparel               48998
Golf                  33220
Footwear              14525
Outdoors               9686
Fitness                2479
Discs Shop             2026
Technology             1465
Pet Shop                492
Book Shop               405
Health and Beauty       362
Name: count, dtype: int64

---Market---
Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

---Order City---
Order City
Santo Domingo     2211
New York City     2202
Los Angeles       1845
Tegucigalpa       1783
Managua           1682
Mexico City       1484
Manila            1381
Philadelphia      1302
San Francisco     1297
London            1187
San Salvador      1135
Seattle           1066
Viena             1038
Yakarta           1006
Berlín             995
Buenos Aires       967
Lagos              903
San Pedro Sula     897
Bangkok            889
Houston            875
Name: count, dtype: int64

---Order Country---
Order Country
Estados Unidos          24840
Francia                 13222
México                  13172
Alemania                 9564
Australia                8497
Brasil                   7987
Reino Unido              7302
China                    5758
Italia                   4989
India                    4783
Indonesia                4204
España                   3868
El Salvador              3726
República Dominicana     3669
Honduras                 3629
Cuba                     3534
Turquía                  3395
Nicaragua                3046
Guatemala                2778
Nigeria                  2309
Name: count, dtype: int64

---Order Region---
Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Name: count, dtype: int64

---Order State---
Order State
Inglaterra                     6722
California                     4966
Isla de Francia                4580
Renania del Norte-Westfalia    3303
San Salvador                   3055
Nueva York                     2753
Distrito Federal               2559
Texas                          2446
Nueva Gales del Sur            2370
Santo Domingo                  2211
Queensland                     2186
Guatemala                      2109
São Paulo                      2031
Provenza-Alpes-Costa Azul      1842
Capital Nacional               1837
Managua                        1834
Francisco Morazán              1783
Panamá                         1631
Victoria                       1456
Pensilvania                    1406
Name: count, dtype: int64

---Order Status---
Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

---Product Name---
Product Name
Perfect Fitness Perfect Rip Deck                 24515
Nike Men's CJ Elite 2 TD Football Cleat          22246
Nike Men's Dri-FIT Victory Golf Polo             21035
O'Brien Men's Neoprene Life Vest                 19298
Field & Stream Sportsman 16 Gun Fire Safe        17325
Pelican Sunstream 100 Kayak                      15500
Diamondback Women's Serene Classic Comfort Bi    13729
Nike Men's Free 5.0+ Running Shoe                12169
Under Armour Girls' Toddler Spine Surge Runni    10617
Fighting video games                               838
Children's heaters                                 652
Summer dresses                                     650
Web Camera                                         592
Toys                                               529
Adult dog supplies                                 492
Lawn mower                                         484
Porcelain crafts                                   484
DVDs                                               483
Dell Laptop                                        442
Rock music                                         434
Name: count, dtype: int64

---Shipping Mode---
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

Check categorical consistency

In [14]:
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    print(col, df[col].astype(str).str.strip().ne(df[col].astype(str)).sum())

Type 0
Delivery Status 0
Category Name 1475
Customer City 0
Customer Country 0
Customer Fname 0
Customer Lname 0
Customer Segment 0
Customer State 0
Customer Street 1829
Department Name 362
Market 0
Order City 0
Order Country 0
Order Region 17925
Order State 0
Order Status 0
Product Name 1774
Shipping Mode 0

Count of Unique values in numerical columns

In [15]:
num_cols = df.select_dtypes(include=['int64','float64']).columns
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    print(f"{col}: {outliers} outliers")

Days for shipping (real): 0 outliers
Days for shipment (scheduled): 0 outliers
Benefit per order: 18942 outliers
Sales per customer: 1943 outliers
Late_delivery_risk: 0 outliers
Category Id: 0 outliers
Customer Id: 1198 outliers
Customer Zipcode: 0 outliers
Department Id: 362 outliers
Latitude: 9 outliers
Longitude: 1414 outliers
Order Customer Id: 1198 outliers
Order Id: 0 outliers
Order Item Cardprod Id: 0 outliers
Order Item Discount: 7537 outliers
Order Item Discount Rate: 0 outliers
Order Item Id: 0 outliers
Order Item Product Price: 2048 outliers
Order Item Profit Ratio: 17300 outliers
Order Item Quantity: 0 outliers
Sales: 488 outliers
Order Item Total: 1943 outliers
Order Profit Per Order: 18942 outliers
Product Card Id: 0 outliers
Product Category Id: 0 outliers
Product Price: 2048 outliers

df.describe().T

In [16]:
df.loc[
    df["Benefit per order"] == df["Benefit per order"].min(),
    ["Benefit per order", "Sales", "Order Item Discount",
     "Order Item Profit Ratio", "Order Id", "Product Name"]
]

,Benefit per order,Sales,Order Item Discount,Order Item Profit Ratio,Order Id,Product Name
63990,"-4,274.98","1,999.99",100.00,-2.25,68859,SOLE E35 Elliptical

In [17]:
df.loc[
    df["Order Item Discount"] == df["Order Item Discount"].max(),
    ["Order Item Discount", "Order Item Discount Rate",
     "Order Item Product Price", "Product Price",
     "Sales", "Order Item Total", "Product Name"]
]

,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Product Price,Sales,Order Item Total,Product Name
12606,500.00,0.25,"1,999.99","1,999.99","1,999.99","1,499.99",SOLE E35 Elliptical

In [18]:
df['Expected Discount'] = df['Order Item Discount Rate'] * df['Order Item Product Price']
df[["Order Item Discount", "Expected Discount"]].head(10)

   Order Item Discount  Expected Discount
0                13.11              13.11
1                16.39              16.39
2                18.03              19.66
3                22.94              22.94
4                29.50              29.50
5                32.78              32.78
6                39.33              39.33
7                42.61              42.61
8                49.16              49.16
9                52.44              52.44

In [19]:
df["Discount Difference"] = (
    df["Order Item Discount"] -
    df["Expected Discount"]
)

df["Discount Difference"].describe()

count   180,519.00
mean          6.30
std          11.80
min         -10.00
25%           0.00
50%           0.00
75%           8.00
max         100.00
Name: Discount Difference, dtype: float64

In [20]:
df["Profit Margin"] = (
    df["Order Profit Per Order"] / df["Sales"]
) * 100

In [21]:
df['expected total'] = df['Order Item Product Price'] - df["Order Item Discount"]
df[['Order Item Total','expected total']].head()

   Order Item Total  expected total
0            314.64          314.64
1            311.36          311.36
2            309.72          309.72
3            304.81          304.81
4            298.25          298.25

In [22]:
df['Delivery Delay'] = df['Days for shipping (real)'] - df['Days for shipment (scheduled)']
df["Delivery Delay"].value_counts().sort_index()

Delivery Delay
-2    21666
-1    21700
 0    33753
 1    60647
 2    28718
 3     7052
 4     6983
Name: count, dtype: int64

In [23]:
pd.crosstab(
    df["Delivery Delay"] > 0,
    df["Late_delivery_risk"]
)

Late_delivery_risk      0      1
Delivery Delay
False               77119      0
True                 4423  98977

In [24]:
df.drop(columns=['expected total','Discount Difference','Expected Discount'],inplace=True)

In [27]:
df['Orders Month'] = df['order date (DateOrders)'].dt.month_name()

In [28]:
df['Orders Year'] = df['order date (DateOrders)'].dt.to_period('Y')

In [30]:
df.to_csv(r"C:\Users\Yash Rajput\Desktop\DataCo\cleaned_DataCo.csv",index=False)